{"uuid": "b4089681-6f6e-4272-9f39-e4f95c5413c3", "children": ["7002e6f6-8662-4ecd-8cb6-dba32de0f916"], "befores": [{"name": "database_base_configuration", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '10.66.8.200' (timed out)\")\n", "trace": "  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/kouhui/Desktop/自动化文件/ui-automatic/testCases/conftest.py\", line 10, in database_base_configuration\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/Utils/operateDatabaseData.py\", line 31, in delete_database_data_test_ci\n    db=db_name)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 325, in __init__\n    self.connect()\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 630, in connect\n    raise exc\n"}, "steps": [{"name": "清空数据库", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '10.66.8.200' (timed out)\")\n", "trace": "  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/Utils/operateDatabaseData.py\", line 31, in delete_database_data_test_ci\n    db=db_name)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 325, in __init__\n    self.connect()\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 630, in connect\n    raise exc\n"}, "start": 1577670569096, "stop": 1577670579126}], "start": 1577670569096, "stop": 1577670579130}], "start": 1577670569096, "stop": 1577670579398}