{"uuid": "40506ce6-54c8-4f3c-8f17-ac8f57db7c22", "children": ["29046ec9-3eb7-4704-9daa-204f60b68ff3"], "befores": [{"name": "database_base_configuration", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '10.66.8.200' (timed out)\")\n", "trace": "  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/_pytest/fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/kouhui/Desktop/自动化文件/ui-automatic/testCases/conftest.py\", line 10, in database_base_configuration\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/Utils/operateDatabaseData.py\", line 31, in delete_database_data_test_ci\n    db=db_name)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 325, in __init__\n    self.connect()\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 630, in connect\n    raise exc\n"}, "steps": [{"name": "清空数据库", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '10.66.8.200' (timed out)\")\n", "trace": "  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/kouhui/Desktop/automatic/ui-automatic/Utils/operateDatabaseData.py\", line 31, in delete_database_data_test_ci\n    db=db_name)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 325, in __init__\n    self.connect()\n  File \"/Users/kouhui/Documents/python/ui-automation/venv/lib/python3.6/site-packages/pymysql/connections.py\", line 630, in connect\n    raise exc\n"}, "start": 1577355074553, "stop": 1577355084591}], "start": 1577355074553, "stop": 1577355084595}], "start": 1577355074553, "stop": 1577355084871}