{"name": "test_account_wrong_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert '登录信息有误，请确认后重新登录111' in '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t'\n +  where '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t' = <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x1087f9b38>>()\n +    where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x1087f9b38>> = <OperationalLayer.Login.login.LoginOperate object at 0x1087f9b38>.validate_account_not_exist", "trace": "self = <test_cases.test_login.test_login.TestLogin object at 0x1087fe9b0>, state_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x1087f9b38>\n\n    @allure.story('这是一个测试账号错误登录的case')\n    def test_account_wrong_login(self, state_login_class):\n        '''\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        '''\n        state_login_class.get_login_url()\n        state_login_class.input_account(abnormal_login_data.account, abnormal_login_data.password,\n                                        abnormal_login_data.verification_code)\n        state_login_class.confirm_login_button()\n        time.sleep(1)\n>       assert '登录信息有误，请确认后重新登录111' in state_login_class.validate_account_not_exist()\nE       AssertionError: assert '登录信息有误，请确认后重新登录111' in '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t'\nE        +  where '\\n\\t\\t\\t\\t\\t\\t登录信息有误，请确认后重新登录\\n\\t\\t\\t\\t\\t' = <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x1087f9b38>>()\nE        +    where <bound method LoginOperate.validate_account_not_exist of <OperationalLayer.Login.login.LoginOperate object at 0x1087f9b38>> = <OperationalLayer.Login.login.LoginOperate object at 0x1087f9b38>.validate_account_not_exist\n\ntest_cases/test_login/test_login.py:41: AssertionError"}, "description": "\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "passed", "start": 1577339933927, "stop": 1577339935931}, {"name": "步骤2：输入账号，密码，验证码", "status": "passed", "parameters": [{"name": "account", "value": "'admin1'"}, {"name": "password", "value": "'admin123'"}, {"name": "verification_code", "value": "'1111'"}], "start": 1577339935932, "stop": 1577339936581}, {"name": "步骤3：点击登录按钮", "status": "passed", "start": 1577339936581, "stop": 1577339936677}, {"name": "步骤4：获取账号不存在报错信息", "status": "passed", "start": 1577339937681, "stop": 1577339937704}], "attachments": [{"name": "stdout", "source": "3f860908-f8e9-41d4-9be7-9112db7fe72c-attachment.txt", "type": "text/plain"}], "start": 1577339933926, "stop": 1577339937705, "uuid": "90166164-859b-442c-a15d-17cd37b9b333", "historyId": "b308178dd37a299f6d4684f5efc4274c", "testCaseId": "1a9d587fd15c0e192eb1d219417b90b6", "fullName": "test_cases.test_login.test_login.TestLogin#test_account_wrong_login", "labels": [{"name": "story", "value": "这是一个测试账号错误登录的case"}, {"name": "feature", "value": "登录"}, {"name": "parentSuite", "value": "test_cases.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "kouhuideMacBook-Air.local"}, {"name": "thread", "value": "4556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login.test_login"}]}