{"name": "test_account_wrong_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <test_cases.test_login.test_login.TestLogin object at 0x000001C7264835F8>\nstate_login_class = <OperationalLayer.Login.login.LoginOperate object at 0x000001C7264F9828>\n\n    @allure.story('这是一个测试账号错误登录的case')\n    def test_account_wrong_login(self, state_login_class):\n        '''\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        '''\n        state_login_class.get_login_url()\n        state_login_class.input_account(abnormal_login_data.account, abnormal_login_data.password,\n>                                       abnormal_login_data.verification_code)\n\ntest_cases\\test_login\\test_login.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nOperationalLayer\\Login\\login.py:23: in input_account\n    self.send_keys(LoginElement.account_input_box, account)\nBase\\base.py:45: in send_keys\n    ele = self.find_element(locator)\nBase\\base.py:29: in find_element\n    ele = WebDriverWait(self.driver, self.timeout, self.t).until(EC.presence_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"a349d2b121a2b34d96554e4e58427575\")>\nmethod = <selenium.webdriver.support.expected_conditions.presence_of_element_located object at 0x000001C7264F9C88>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nc:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "description": "\n        用例描述：输入错误管理员账号，正确密码，验证码（随便），登录报错\n        :return:\n        ", "steps": [{"name": "步骤1：到达登录页面", "status": "passed", "start": 1579483301509, "stop": 1579483303625}, {"name": "步骤2：输入账号，密码，验证码", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\automatic\\ui-automatic\\OperationalLayer\\Login\\login.py\", line 23, in input_account\n    self.send_keys(LoginElement.account_input_box, account)\n  File \"E:\\automatic\\ui-automatic\\Base\\base.py\", line 45, in send_keys\n    ele = self.find_element(locator)\n  File \"E:\\automatic\\ui-automatic\\Base\\base.py\", line 29, in find_element\n    ele = WebDriverWait(self.driver, self.timeout, self.t).until(EC.presence_of_element_located(locator))\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "account", "value": "'admin1'"}, {"name": "password", "value": "'admin123'"}, {"name": "verification_code", "value": "'1111'"}], "start": 1579483303625, "stop": 1579483308714}], "attachments": [{"name": "stdout", "source": "5a1e6987-247f-4ed2-814f-630913835a62-attachment.txt", "type": "text/plain"}], "start": 1579483301509, "stop": 1579483308714, "uuid": "2df83e58-1402-4505-8cba-9abf568794a2", "historyId": "b308178dd37a299f6d4684f5efc4274c", "testCaseId": "1a9d587fd15c0e192eb1d219417b90b6", "fullName": "test_cases.test_login.test_login.TestLogin#test_account_wrong_login", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "这是一个测试账号错误登录的case"}, {"name": "parentSuite", "value": "test_cases.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-IJ0L9OR"}, {"name": "thread", "value": "21552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login.test_login"}]}